## Music and a sound effect. SPACE plays the effect, P pauses and resumes the
## music, up and down change the master volume, left and right pan the effect,
## and [ and ] change the music pitch. ESC quits.
##
## The audio files are generated by examples/assets/gen_assets.nim.

import std/[os, strutils, math]
import nim2d

const
  W = 720
  H = 480

let n2d = newNim2d("nim2d - audio", 140, 90, W.cint, H.cint, (16'u8, 18'u8, 28'u8, 255'u8))
let font = newFont(getAppDir() / "font.ttf", 20)
n2d.setFont(font)

let music = n2d.newSource(getAppDir() / "assets" / "music.wav", stStream)
let blip = n2d.newSource(getAppDir() / "assets" / "blip.wav", stStatic)
music.setLooping(true)
music.setVolume(0.6)

var master = 1.0
var pan = 0.0
var pitch = 1.0

n2d.load = proc(nim2d: Nim2d) =
  music.play()

n2d.keydown = proc(nim2d: Nim2d, sc: SDL_Scancode) =
  case sc
  of SDL_SCANCODE_ESCAPE: nim2d.running = false
  of SDL_SCANCODE_SPACE:
    blip.setPosition(pan, 0)
    blip.play()
  of SDL_SCANCODE_P:
    if music.isPaused: music.resume() else: music.pause()
  of SDL_SCANCODE_UP:
    master = min(1.5, master + 0.1)
    nim2d.setVolume(master)
  of SDL_SCANCODE_DOWN:
    master = max(0.0, master - 0.1)
    nim2d.setVolume(master)
  of SDL_SCANCODE_LEFT:
    pan = max(-6.0, pan - 1.0)
    blip.setPosition(pan, 0)
    blip.play()
  of SDL_SCANCODE_RIGHT:
    pan = min(6.0, pan + 1.0)
    blip.setPosition(pan, 0)
    blip.play()
  of SDL_SCANCODE_LEFTBRACKET:
    pitch = max(0.5, pitch - 0.1)
    music.setPitch(pitch)
  of SDL_SCANCODE_RIGHTBRACKET:
    pitch = min(2.0, pitch + 0.1)
    music.setPitch(pitch)
  else: discard

n2d.draw = proc(nim2d: Nim2d) =
  nim2d.setColor(240, 240, 250)
  nim2d.print("audio: " & (if nim2d.audioAvailable: "on" else: "off (no device)"), 16, 16)
  nim2d.setColor(150, 160, 180)
  nim2d.print("SPACE sfx   P pause music   up/down volume   left/right pan   [ ] pitch", 16, 44)
  nim2d.setColor(200, 220, 255)
  nim2d.print("master volume: " & formatFloat(master, ffDecimal, 2), 16, 90)
  nim2d.print("music playing: " & $music.isPlaying() & "   pitch: " & formatFloat(pitch, ffDecimal, 2), 16, 118)
  nim2d.print("music position: " & formatFloat(music.tell, ffDecimal, 1) & " / " &
              formatFloat(music.duration, ffDecimal, 1) & " s", 16, 146)
  nim2d.print("sfx pan: " & formatFloat(pan, ffDecimal, 1), 16, 174)

n2d.play()
